src/myfirsttry/forums/urls.py
# from pages import views
# from pages.views import contact_view, feedback_view, home_view
# from products.views import product_detail_view
# from .views import detail_view,category_view,list_view
# from .views import  ListView ,CategoryView, DetailView
# from django.contrib.auth.views import LoginView

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView

from .views import (CategoryView, ForumPostCreateView, ForumPostDetailView,
                    HomeView)

app_name = 'forums'

urlpatterns = [
    path('',HomeView.as_view(template_name='forums/forumpost_list_index.html'), name = "homepage"),
    path('create-forum/',ForumPostCreateView.as_view(),name = "create"),
    path('c/<str:category>/',CategoryView.as_view(template_name='forums/forumpost_list.html'), name= "category"),  
    path('s/<slug:slug>/',ForumPostDetailView.as_view(template_name='forums/forumpost_detail.html'), name = "detail"),

    path('d/',TemplateView.as_view(template_name='forums/contact.html'),name = "contact"),


    # path('login/',LoginView.as_view())  #/forum//login/

    # path('about/',about_view),

]
if settings.DEBUG: 
    # from django.conf.urls.static import static
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/myfirsttry/myfirsttry/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import include, path, re_path

from pages.views import contact_view, feedback_view, home_view
from products.views import product_detail_view

    # from pages import views




urlpatterns = [
    #for forum
    path('forums/',include('forums.urls',namespace="forums")),   # forums:home
    path('admin/', admin.site.urls),
    path('', home_view),


    path('login/',LoginView.as_view(),name = "login"),
    path('logout/',LogoutView.as_view(),name = "logout"),
    # path('logout/',LogoutView.as_view(),name = "logout"),
    path('password-reset/',PasswordResetView.as_view(),name = "password_reset"),



    re_path(r'^contacts?/$', contact_view),
    path('feedback/', feedback_view),
    path('detail/',product_detail_view),


]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/myfirsttry/forums/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.conf import settings  
from django.urls import reverse
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType

User = settings.AUTH_USER_MODEL 

# Create your models here.
class ForumPost(models.Model):

    # user = modes.Foreignkey(User,default=1, null=true, on_delete=models.SET)
    image = models.ImageField(upload_to = 'media/', blank = True, null=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE,blank=True)
    topic = models.CharField(max_length = 150)
    category = models.CharField(max_length = 50)
    message = models.TextField()
    slug = models.SlugField(blank = True, null=True)
    # message_timings = models.DateTimeField(auto_now_add=True)   //replaced by timestamp
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now = True)
    
    
#---------------these are subclasses-----------------

    class Meta:
        ordering = ['-updated','-timestamp']


#-----------------these are methods----------------

    def get_absolute_url(self):
        return reverse('forums:detail', kwargs={"slug" : self.slug})

    def __str__(self):
        return self.topic

#-----------these are properties----------------

    @property 
    def title(self):
        return(self.topic)
    
    @property
    def get_comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs 

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type
    

#-----------------these are signals-------------

def fo_pre_save_reciever(sender,instance,*args,**kwargs):
    # print("saving...")
    # print(instance.timestamp)
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


def fo_post_save_reciever(sender,instance,created,*args,**kwargs):
    # print("saved")
    # print(instance.timestamp)
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
        instance.save()

pre_save.connect(fo_pre_save_reciever,sender=ForumPost)
post_save.connect(fo_post_save_reciever,sender=ForumPost)

src/myfirsttry/forums/forms.py
from django import forms
from .models import ForumPost


# class ForumPostCreateForm(forms.Form):
#     topic = forms.CharField()
#     category = forms.CharField()
#     message = forms.CharField(widget=forms.Textarea)


class ForumPostModelForm(forms.ModelForm):
    class Meta:
        model = ForumPost
        fields = ['topic','category','message']
    

src/myfirsttry/forums/views.py
from urllib.parse import urlparse

# from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.edit import FormMixin
from django.views.generic.detail import DetailView
from django.contrib.contenttypes.models import ContentType

from django.db.models import Q
# from django.shortcuts import (get_list_or_404, get_object_or_404, redirect,
#                               render)
# from django.utils.http import urlencode
# from django.views import View
from django.views.generic import CreateView, DetailView, ListView
from comments.models import Comment
from comments.forms import CommentForm  

from .forms import ForumPostModelForm
from .models import ForumPost
from django.urls import reverse
from django.http import HttpResponseForbidden

# from comments.models import Comment

all_cat_raw = ForumPost.objects.order_by('category').values_list('category',flat=True).distinct()
all_cat = [urlparse(cat).geturl() for cat in all_cat_raw]



class ForumPostCreateView(LoginRequiredMixin, CreateView):
    form_class = ForumPostModelForm
    login_url = '/login/'
    template_name = "forums/form.html" 
    # success_url = "/forum/"
    

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(ForumPostCreateView,self).form_valid(form)


class HomeView(ListView):
    # def get_context_data(self,*args,**kwargs):
    #     context = super(HomeView,self).get_context_data(*args,**kwargs)
    #     all_obj = ForumPost.objects.all().order_by('-timestamp')
    #     # .filter(topic__icontains = 'c')
    #     #for sorting message by latest and from topic containing c 
    #     list_of_obj = list(all_obj)

    #     print(all_cat)
    #     context = {
    #     "list_of_object": list_of_obj,
    #     "list_of_categories": all_cat}
    #     return context
                                        
    queryset = ForumPost.objects.all().order_by('-timestamp')

    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(**kwargs)
        context['list_of_categories']= all_cat 
        return context

class CategoryView(ListView):
    # def get_context_data(self,*args,**kwargs):
        
    #     all_obj = get_list_or_404( ForumPost,category__icontains = kwargs['category'])
    #     list_of_obj = all_obj

    #     context = {
    #         "list_of_object":list_of_obj,
    #         "list_of_categories": all_cat
        
    #                         }
    #     return context

    def get_queryset(self):
        category = self.kwargs.get('category')
        if category :
            queryset = ForumPost.objects.filter(
                Q(category__iexact = category) |
                Q(category__icontains= category)  
                )
        else:
            queryset = ForumPost.objects.none()
        return queryset

    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(**kwargs)
        context['list_of_categories']= all_cat 
        return context


class ForumPostDetailView(FormMixin,DetailView):
    model = ForumPost  
    form_class = CommentForm
#what to show to the show before the user fills the form (prefilled data)
    def get_initial(self):
        instance = self.get_object()
        initial_data = {
            "object_id": instance.id,
            "content_type": instance.get_content_type.id
        }
        return initial_data
#what you do after new commet has bee created
    def get_success_url(self):
        return reverse('forums:detail',kwargs={'slug':self.object.slug})
#getting data from form filled by user
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        self.object = self.get_object()

        comment_form = self.get_form()

        if comment_form.is_valid():
            return self.form_valid(comment_form)

        else:
            return self.form_invalid(comment_form)
#create a comment
    def form_valid(self, form):
        parent_obj = None
        parent_id = None

        try : 
            parent_id = int(self.request.POST.get("parent_id"))
        except : 
            parent_id = None
        if parent_id : 
            parent_qs = Comment.objects.filter(id = parent_id)
            if parent_qs.exists():
                parent_obj = parent_qs.first()


        
        input_content_type = form.cleaned_data.get("content_type")
        # print(input_content_type)
        content_type = ContentType.objects.get(id=input_content_type)

        obj_id = form.cleaned_data.get('object_id')

        content_data = form.cleaned_data.get("content")


        new_comment, created = Comment.objects.get_or_create(user = self.request.user,content_type= content_type,object_id = obj_id,content = content_data,parent = parent_obj)
         
        
        return super().form_valid(form)
        
        
    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(**kwargs)
        context['list_of_categories'] = all_cat
    
        # instance = self.get_object()

        # cont_type = ContentType.objects.get_for_model(ForumPost)
        # # print(self.get_object().id)
        # obj_id = self.get_object().id

        # comments = Comment.objects.filter_by_instance(instance)
        # context['comments'] = comments  

    # context['comments'] = Comment.objects.filter(forum=context.get('object'))
    # print(context)


 
        # obj = get_object_or_404(ForumPost, slug=kwargs['slug'])
        # print(obj)
        # context = {
        #     "object" : obj,
        #     "list_of_categories": all_cat

        #         }
            
    #     print(args,kwargs)
        # print("Djando does",request.method,request.path,request.user)
        
        return context


#-----------------------------------------------------------------
# Create your views here.
#CRUD




            
# def list_view(request,*args,**kwargs):
    
#     all_obj = ForumPost.objects.all().order_by('-timestamp')
#     # .filter(topic__icontains = 'c')
# #for sorting message by latest and from topic containing c 
#     list_of_obj = list(all_obj)

#     print(all_cat)
#     context = {
#         "list_of_object": list_of_obj,
#         "list_of_categories": all_cat
#     }

#     return render(request, "forums/index.html",context)


# Create your views here.
# def category_view(request,*args,**kwargs):

    
#     all_obj = get_list_or_404( ForumPost,category__icontains = kwargs['category'])
#     list_of_obj = all_obj

#     context = {
#         "list_of_object":list_of_obj,
#         "list_of_categories": all_cat
        
#     }
     
    
#     return render(request, "forums/index.html",context)


# Create your views here.
# def detail_view(request,*args,**kwargs):
    
#     obj = get_object_or_404(ForumPost, slug=kwargs['slug'])
#     print(obj)
#     context = {
#         "object" : obj,
#         "list_of_categories": all_cat

#     }
    
#     print(args,kwargs)
#     print("Djando does",request.method,request.path,request.user)
    
#     return render(request, "forums/detail.html",context)
# #CRUD 
# def forumpost_retrieve_view(request,*args,**kwargs):


# def forumpost_update_view(request,*args,**kwargs):
# def forumpost_create_view(request,*args,**kwargs):
#     cotext ={'form':None}
#     return render(request,forum/create.html,context)
# def forumpost_delete_view(request,*args,**kwargs):

#just a dummy 
# def contact_view(request,*args,**kwargs):
    
    
#     context = {
        
#     } 

# class ContactView(TemplateView):
#     template_name = 'contact.html'

#     def get_context_data(self,*args,**kwargs):
#         context = super(ContactView,self).get_context_data(*args,**kwargs)
#         print(context)
#         return context

    
# class ContactTemplateView(TemplateView):
#     template_name = 'contact.html'

#------------------------------------------------------------------------



# @login_required()#login_url = '/login/'
# def forumpost_createview(request):
#     template_name = "forums/form.html"
#     form = ForumPostModelForm(request.POST or None)
#     error = None
#     if form.is_valid():
#         print('abhi wala user',request.user.is_authenticated)
#         if request.user.is_authenticated:
#             instance = form.save(commit=False)
#             instance.owner = request.user
#             instance.save()
            
#             # obj = ForumPost.objects.create(**form.cleaned_data)
#             # obj = form.save(commit=False)
#             # obj.topic = form.cleaned_data.get("topic") 
#             # obj.save()

#             form = ForumPostModelForm()
            
#             return redirect('/forum/')
#         else:
#             return redirect('/login/')
#     else:
#         error = form.errors
#     context ={"form" : form, "error":error}
#     return render(request, template_name,context)

src/myfirsttry/forums/templates/forums/bass.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.0/litera/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <!-- <link rel="stylesheet" href="assets/css/style.css"> -->

    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>






    <title>not mine </title>
</head>

<body>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="{% url 'forums:homepage' %}">Forum</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="nav-link" href="{% url 'forums:create' %}"> <i class="fa fa-plus"
                            aria-hidden="true"></i>Add</a>




                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'forums:homepage' %}">Home <span
                                        class="sr-only">(current)</span></a>
                                <!--for list view -->
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <!-- Dropdown for category  -->category

                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    {% for category in list_of_categories %}
                                    <!-- <a class="dropdown-item" href="/forum/c/{{ cat|urlencode }}">{{ cat }}</a> -->
                                    <a class="dropdown-item"
                                        href="{% url 'forums:category' category  %}">{{ category }}</a> {% endfor %}

                                    <!-- <a class="dropdown-item" href="#">Something else here</a> -->
                                </div>
                            </li>
                            <!-- <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li> -->
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                            <!--detail view -->
                        </form>{% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="btn" href="{% url 'logout' %}">Logout</a>
                        </li>
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <br><br>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {% block content %} {% endblock content %}

            </div>
        </div>
    </div>
































































</body>


</html>

src/myfirsttry/forums/templates/forums/form.html
{% extends 'forums/bass.html' %} {% block content %}
<form action="{% url 'forums:create' %}" method="POST"> {% csrf_token %}
    <!-- <div class="form-group">
        <label for="topic">Topic</label>
        <input type="text" class="form-control" id="topic" name="topic" placeholder="MyTopic">
    </div>
    <div class="form-group">
        <label for="category">Category</label>
        <input type="text" class="form-control" id="category" name="category" placeholder="MyCategory">
    </div>
    <div class="form-group">
        <label for="message">Message here!</label>
        <textarea class="form-control" id="message" name="message" rows="3"></textarea>
    </div> -->
    {% if error %} {{ error }} {% endif %} {{ form.as_p }}

    <button type="submit" class="btn btn-default">Send</button>

</form>
{% endblock content %}

src/myfirsttry/forums/templates/forums/forumpost_detail.html
{% extends 'forums/bass.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}
<div class="card mb-4">

    <div class="container-fluid mt-10">
        <div class="row">

            <!-- Portfolio Item Heading -->
            <h1 class="my-4">{{ object.topic }}
            </h1>

            <!-- Portfolio Item Row -->
            <div class="row">
                {% if object.image.isempty %}

                <div class="col-md-4">
                    
                    <img class="img-fluid" src="{{ object.image.url }}" alt="">
                </div>
                {% endif %}

                <div class="col-md-4">
                    <h3 class="my-3"><small>Message : </small>{{ object.message }}</h3>

                    <h3 class="my-3">Category</h3>
                    <ul>
                        <li>{{ object.category }}</li>
                        <li>{{ object.get_content_type }}</li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="card-group">
    <div class="container-fluid mt-100">
        <div class="row">
            <div class="col-md-100">
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="media flex-wrap w-100 align-items-center">
                            <h3>Comments</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt-100"></div>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="media flex-wrap w-100 align-items-center">
                    <img src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1574583246/AAA/2.jpg"
                        class="d-block ui-w-40 rounded-circle" alt="" />
                    <div class="media-body ml-3">
                        <a href="javascript:void(0)" data-abc="true">{{ comment.user.username }}</a>
                        <!-- <div class="text-muted small">{{ comment.timestamp|timesince }}</div> -->
                    </div>
                    <div class="text-muted small ml-3">
                        <!-- <div>Member since <strong>{{ comment.user.date_joined }}</strong></div>
                        <div><strong>{{ comment.user.forumpost_set.count }}</strong> posts</div> -->
                    </div>
                </div>
            </div>

            <form method="POST" action=".">
                <div class="card-body">
                    {% csrf_token %} {{ form|crispy }}
                    <!-- <p>
                        <h4>Category :</h4> {{ comment.content_object }}
                    </p> -->
                </div>
                <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                    <!-- <div class="px-4 pt-3">
                    <a href="javascript:void(0)" class="text-muted d-inline-flex align-items-center align-middle" data-abc="true">
                        <i class="fa fa-heart text-danger"></i>&nbsp;
                    </a>
                    <span class="align-middle">445</span>
                    <span class="text-muted d-inline-flex align-items-center align-middle ml-4">
                    <i class="fa fa-eye text-muted fsize-3"></i>&nbsp;
                    <span class="align-middle">14532</span>
                    </span>
                   </div> -->
                    <div class="px-4 pt-3">
                        <button type="submit" class="btn btn-primary"><i class="ion ion-md-create"></i>&nbsp; Add
                            Comment</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% for comment in object.get_comments %}
<div class="container-fluid mt-100"></div>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="media flex-wrap w-100 align-items-center">
                    <img src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1574583246/AAA/2.jpg"
                        class="d-block ui-w-40 rounded-circle" alt="" />
                    <div class="media-body ml-3">
                        <a href="javascript:void(0)" data-abc="true">{{ comment.user.username }}</a>
                        <div class="text-muted small">{{ comment.timestamp|timesince }}</div>
                    </div>
                    <div class="text-muted small ml-3">
                        <div>Member since <strong>{{ comment.user.date_joined }}</strong></div>
                        <div><strong>{{ comment.user.forumpost_set.count }}</strong> posts</div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p>
                    {{ comment.content }}

                </p>
                <!-- <p>
                        <h4>Category :</h4> {{ comment.content_object }}
                    </p> -->
            </div>
            <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                <div class="px-4 pt-3">
                    <a href="javascript:void(0)" class="text-muted d-inline-flex align-items-center align-middle"
                        data-abc="true">
                        <i class="fa fa-heart text-danger"></i>&nbsp;
                    </a>
                    <span class="align-middle">445</span>
                    <span class="text-muted d-inline-flex align-items-center align-middle ml-4">
                        <i class="fa fa-eye text-muted fsize-3"></i>&nbsp;
                        <span class="align-middle">14532</span>
                    </span>
                </div>
                <div class="px-4 pt-3">
                    <button type="button" class="comment-reply-btn" class="btn btn-primary">
                        <i class="ion ion-md-create"></i>&nbsp; Reply
                    </button>
                </div>
            </div>
            <!-- <hr> -->
            <div style="margin-left: 4rem; margin-right : 4rem">
                <div style="display:none;" class="add_reply card mb-4">
                    <div class="card-header">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1574583246/AAA/2.jpg"
                                class="d-block ui-w-40 rounded-circle" alt="" />
                            <div class="media-body ml-3">
                                <a href="javascript:void(0)" data-abc="true">{{ comment.user.username }}</a>
                                <!-- <div class="text-muted small">{{ comment.timestamp|timesince }}</div> -->
                            </div>
                            <div class="text-muted small ml-3">
                                <!-- <div>Member since <strong>{{ comment.user.date_joined }}</strong></div>
                            <div><strong>{{ comment.user.forumpost_set.count }}</strong> posts</div> -->
                            </div>
                        </div>
                    </div>

                    <form method="POST" action=".">
                        <div class="card-body">
                            {% csrf_token %} {{ form|crispy }}
                            <input type="hidden" name="parent_id" value="{{ comment.id }}" />
                            <!-- <p>
                            <h4>Category :</h4> {{ comment.content_object }}
                        </p> -->
                        </div>
                        <div
                            class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                            <!-- <div class="px-4 pt-3">
                        <a href="javascript:void(0)" class="text-muted d-inline-flex align-items-center align-middle" data-abc="true">
                            <i class="fa fa-heart text-danger"></i>&nbsp;
                        </a>
                        <span class="align-middle">445</span>
                        <span class="text-muted d-inline-flex align-items-center align-middle ml-4">
                        <i class="fa fa-eye text-muted fsize-3"></i>&nbsp;
                        <span class="align-middle">14532</span>
                        </span>
                       </div> -->
                            <div class="px-4 pt-3">
                                <button type="submit" class="btn btn-primary"><i class="ion ion-md-create"></i>&nbsp;
                                    Add
                                    Comment</button>
                            </div>
                        </div>
                    </form>
                </div>

                <br>

                <!-- Child Comments code is here! -->
                {% for child in comment.children  %}

                <div class="card mb-4">
                    <div class="card-header">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1574583246/AAA/2.jpg"
                                class="d-block ui-w-40 rounded-circle" alt="" />
                            <div class="media-body ml-3">
                                <a href="javascript:void(0)" data-abc="true">{{ child.user.username }}</a>
                                <div class="text-muted small">{{ child.timestamp|timesince }}</div>
                            </div>
                            <div class="text-muted small ml-3">
                                <div>Member since <strong>{{ child.user.date_joined }}</strong></div>
                                <div><strong>{{ child.user.forumpost_set.count }}</strong> posts</div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ child.content }}

                        </p>
                    </div>
                    <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                        <div class="px-4 pt-3">
                            <a href="javascript:void(0)"
                                class="text-muted d-inline-flex align-items-center align-middle" data-abc="true">
                                <i class="fa fa-heart text-danger"></i>&nbsp;
                            </a>
                            <span class="align-middle">445</span>
                            <span class="text-muted d-inline-flex align-items-center align-middle ml-4">
                                <i class="fa fa-eye text-muted fsize-3"></i>&nbsp;
                                <span class="align-middle">14532</span>
                            </span>
                        </div>
                        <!-- <div class="px-4 pt-3">
                            <button type="button" class="btn btn-primary">
                                <i class="ion ion-md-create"></i>&nbsp; Reply
                            </button>
                        </div> -->
                    </div>


                </div>

                {% endfor %}

            </div>

        </div>
    </div>
</div>
{% endfor %}
</div>

<script>
    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().parent().next("div").children(0).fadeToggle();
    })
</script>
{% endblock content %}